twitter: &twitter
  twitter_api_key: <%= ENV["API_KEY"] %>
  twitter_api_secret: <%= ENV["API_SECRET"] %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *twitter

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *twitter


google_client_id: 291889273769-2olbb04p21jmago8gklifp3juo70a2b3.apps.googleusercontent.com
google_client_secret: M0RotaQnj9XfxarpQOT0-84a

twitter_api_key: S5IMnuLPPhMKyZ7LdGi02AIVr
twitter_api_secret: WprUq5jCLDEDWD2L2KhuxrOXl36a0LmL9Eo0vFhykhrM8xqKEn

facebook_key: 643316072821629
facebook_secret: 3f51c11b1221d56fe045056bf04da74b